services:
  app:
    image: logistics-docker-image
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    depends_on:
      - dynamodb
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"